services:
  express-server:
    build: ./server
    container_name: express-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - elk-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    depends_on:
      - logstash
    restart: always

  caddy:
    image: caddy/caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - elk-network
    depends_on:
      - express-server
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2 # Updated to latest LTS
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network
    deploy:
      resources:
        limits:
          memory: 1024M

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2 # Updated to latest LTS
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk-network
    deploy:
      resources:
        limits:
          memory: 512M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2 # Updated to latest LTS
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-network
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - logstash
      - elasticsearch

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15 # Updated to latest LTS
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  elk-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  pg_data:
